# dev test stage prod
prod:
  线索ID: '236911665074604'
  子任务线索id : '26285888265960'
  子任务phone : "18210233933"
  服务中 : "服务中"
  服务完成 : "服务完成"
  服务取消 : "服务取消"
  试驾任务 : "试驾任务"
  舱任务 : "舱任务"
  4s店任务 : "4s店任务"
  上门任务 : "上门任务"

